### PR TITLE
Ex1 toffoli gate translation in Hindi

### PR DESCRIPTION
**Pull request by ishagholkar-qiskit**
1) Created ex1-hi.ipynb for the example translation in Hindi.
2) Translated the text lines in relevant words with localisation.
3)Raised PR

### CODE REVIEW

**Comment by starktech23** [comment]
Formatting issues in file, please stand by for update.

**Comment by HuangJunye** [comment]
Sorry for the delay. Thank you very much for your submission!

**Comment by HuangJunye** [comment]
@ishagholkar-qiskit @starktech23 Do you know how to fix the formatting issue?

**Comment by starktech23** [comment]
@HuangJunye yes I'm working on it with @ishagholkar-qiskit, could you please undo this merge so that we may update the PR?

**Comment by HuangJunye** [comment]
@starktech23 Thanks a lot! I’ll undo the merge tomorrow and let you know when I am done.

**Comment by HuangJunye** [comment]
@starktech23 @ishagholkar-qiskit The PR is reverted. Please make a new PR when it's ready. Thank you!

**Pull request merged**
