### PR TITLE
EX1

### PR DESCRIPTION
**Pull request by Innanov**
Ex 1
By INNAN Nouhaila 
Cost: 79

### CODE REVIEW

**Comment by Innanov** [comment]
Ex2
Cost: 49

**Comment by Innanov** [comment]
Ex5
Cost: 6

**Comment by Innanov** [comment]
Ex3 
Cost:  246

**Comment by Innanov** [comment]
Ex4

**Comment by HuangJunye** [comment]
Sorry for the delay. Thank you very much for your submission!

**Pull request merged**
